firmware:
  stage: build
  before_script:
    - export PATH=$PATH:/root/zpugcc/toolchain/install/bin
  script: 
    - HDL/gcvideo_dvi/build-all.sh
  artifacts:
    paths:
    - HDL/gcvideo_dvi/binaries/*.zip
  tags:
    - gcvideo
